dist: focal
language: python
matrix:
  include:
    - python: 3.11
cache: pip
services:
  - docker
before_install:
  # nothing needed here yet, containers come pre-installed
install:
  - pip install -r html2md/requirements.txt
before_script:
  - docker build -t html2md-api -f ./html2md/Dockerfile .
  - docker build -t mysql-html2md -f ./html2md/models/Dockerfile .
  - docker run -p 3306:3306 --name mysql-html2md -d mysql-html2md
  - docker run -d -p 127.0.0.1:8080:8080 --name html2md-api --link mysql-html2md:html2md_host html2md-api
  - sleep 10
  - docker exec -i mysql-html2md mysql -uroot -proot < init.sql
script:
  - pytest
deploy:
  provider: script
  script: bash html2md/deploy.sh
  on:
    branch: main
