dist: jammy
language: python
matrix:
  include:
    - python: 3.7
      env: MYSQL_DATABASE=html2md_dev MYSQL_USER=travis MYSQL_PASSWORD=html2md_pwd
    - python: 3.8
      env: MYSQL_DATABASE=html2md_dev MYSQL_USER=travis MYSQL_PASSWORD=html2md_pwd
    - python: 3.11
      env: MYSQL_DATABASE=html2md_dev MYSQL_USER=travis MYSQL_PASSWORD=html2md_pwd
cache: pip
services:
  - mysql
  - docker
before_install:
  - sudo apt-get update
  - sudo apt remove python-pip
  - sudo apt install python-setuptools
  - sudo pip install --upgrade pip
  - sudo apt-get install -y libmysqlclient-dev
install:
  - pip install -r requirements.txt
before_script:
  - docker build -t html2md-api -f Dockerfile .
  - docker build -t mysql-html2md -f html2md/models/Dockerfile .
  - docker run -d -p 3306:3306 --name mysql-test mysql-html2md
  - docker run -d -p 127.0.0.1:8080:8080 --name html2md-api --link mysql-html2md:html2md_host html2md-api
  - sleep 10
  - docker exec -i mysql-html2md mysql -uroot -proot < init.sql
script:
  - pytest
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
