dist: jammy
language: python
matrix:
  include:
    - python: 3.7
      env: MYSQL_DATABASE=html2md_dev MYSQL_USER=travis MYSQL_PASSWORD=html2md_pwd
    - python: 3.8
      env: MYSQL_DATABASE=html2md_dev MYSQL_USER=travis MYSQL_PASSWORD=html2md_pwd
    - python: 3.11
      env: MYSQL_DATABASE=html2md_dev MYSQL_USER=travis MYSQL_PASSWORD=html2md_pwd
cache: pip
services:
  - mysql
  - docker
before_install:
  - sudo apt-get update
  - sudo apt remove python-pip
  - sudo apt install python-setuptools
  - sudo pip install --upgrade pip
  - sudo apt-get install -y libmysqlclient-dev
install:
  - pip install -r requirements.txt --use-feature=fast-debs
before_script:
  - docker build -t html2md-api .
  - docker run -d -p 127.0.0.1:8080:8080 html2md-api
  - mysql -e 'CREATE DATABASE IF NOT EXISTS html2md;'
script:
  - pytest
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
