language: python
python:
  - 3.7


# Specify additional services or addons if needed, such as databases, caches, etc.
services:
  - mysql

# Environment variables for MySQL setup
env:
  global:
    - MYSQL_DATABASE=html2md_dev
    - MYSQL_USER=travis
    - MYSQL_PASSWORD=html2md_pwd

# Install dependencies
install:
  - pip install -r requirements.txt

# Set up MySQL database
before_script:
  - mysql -e 'CREATE DATABASE html2md;'  # Create the database

# Run tests
script:
  - pytest

# Deployment configuration (deploy to Digital Ocean VPS after tests pass)
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main  # Specify the branch you want to deploy from

# You can specify other settings here, such as notifications, environment variables, etc.
# notifications:
#   email:
#     on_success: always
#     on_failure: always
