dist: focal
language: python
matrix:
  include:
    - python: 3.11
cache: pip
services:
  - docker
before_install:
  # nothing needed here yet, containers come pre-installed
install:
  - pip install -r html2md/requirements.txt
  - docker pull mysql
before_script:
  - docker run  --name html2mddb -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -d mysql
  - docker cp init.sql html2mddb:/docker-entrypoint-initdb.d/init.sql
  - sleep 10
script:
  - docker ps
  - docker logs html2mddb
  - pytest
deploy:
  provider: script
  script: - python3 html2md/testsql.py
          - python3 html2md/api/html2md.py
  on:
    branch: main
# Subsequent changes must be made through a pull request
